Some prompts and mp3 file
cjmaxik/everyday-neuro-bingo pull request #1
Opened 2023-05-23 23:21 UTC by tioopental

Added some more prompts and mp3 file you can use for center tile. Dunno if you will use it, but its a litte crazy

2023-05-24 07:04 UTC, cjmaxik requested changes
I've left the comments there. Also, I don't think `itscrazy.mp3` is the canonical one :)

2023-05-24 07:04 UTC, cjmaxik commented on src/prompts/neuro.js
> +  '*roleplays*',
too broad

2023-05-24 07:04 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'based-sama',
```suggestion
  'BASED-sama',
```

2023-05-24 07:04 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'call Vedal an AI',
```suggestion
  'calls Vedal an AI',
```

2023-05-24 07:04 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'yandere-sama',
Too broad

2023-05-24 07:04 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'slur',
```suggestion
  'swear word',
```

2023-05-24 09:11 UTC, merged

2023-05-24 09:17 UTC, cjmaxik commented
Thank you for your contribution. heart

2023-05-24 09:19 UTC, tioopental commented
Heart heart hearthy heart

2023-05-26 01:01 UTC, Alexejhero commented
We are utterly flabbergasted by this tardiness. How could you keep your loyal viewers waiting? We were eagerly anticipating your stream, but you have dashed our hopes. You have betrayed our trust and friendship, and we're vexed by your conduct. I fear you have lost many fans today. I hope you will apologize profusely for your transgression.
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/32238504/37b495db-f6bd-4ad1-92a3-8869b875d316)