Update neuro.js
cjmaxik/everyday-neuro-bingo pull request #4
Opened 2023-05-25 22:35 UTC by tioopental

Added lots more prompts, small corrections

2023-05-25 22:36 UTC, tioopental commented on src/prompts/neuro.js
> -  'ignores bits message',
same as donowalled

2023-05-26 05:06 UTC, cjmaxik requested changes

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'chat spams Vedal\'s catchphrase',
```suggestion
  'chat spams Vedal\'s copypasta',
```

Or maybe
```suggestion
  'this is crazy 🐢',
```
We don't have much space for the sentence.

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'wholesome-sama',
What is this exactly?

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'rickroll-sama',
```suggestion
  'rickrolls',
```

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'chat spams GOODONE',
We already have `funny joke`

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'misgenders random person',
```suggestion
  'misgenders someone',
```

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'believe in the time god',
```suggestion
  'mentions the Time God',
```

2023-05-26 05:06 UTC, cjmaxik commented on src/prompts/neuro.js
> +  'POG',
```suggestion
  'POG / poggers',
```

2023-05-26 06:06 UTC, tioopental commented
Fixed

2023-05-26 06:11 UTC, merged

2023-05-26 06:11 UTC, cjmaxik commented
Thank you. heart