Update and restructure evilNeuro.js
cjmaxik/everyday-neuro-bingo pull request #51
Opened 2023-06-10 21:13 UTC by tioopental

- added/deleted/replaced prompts
- reshuffle

2023-06-10 21:13 UTC, tioopental commented on src/prompts/evilNeuro.js
> -    'mentions China',
prolly one time thing

2023-06-10 21:14 UTC, cjmaxik commented on src/prompts/evilNeuro.js
> -    'mentions China',
Yep

2023-06-10 21:14 UTC, tioopental commented on src/prompts/evilNeuro.js
> -    'asks who Neuro is',
outdated

2023-06-10 21:16 UTC, cjmaxik requested changes

2023-06-10 21:16 UTC, cjmaxik commented on src/prompts/evilNeuro.js
> +    'mentions her missing cat',
```suggestion
    'her cat is missing again',
```
?

2023-06-10 21:16 UTC, cjmaxik commented on src/prompts/evilNeuro.js
>      'chat spams "That\'s evil" copypasta'
I don't think I saw any of that today. Prolly remove.

2023-06-10 21:16 UTC, cjmaxik commented on src/prompts/evilNeuro.js
>      '"GOOD THOUGHTS"',
One time thing too

2023-06-10 21:16 UTC, cjmaxik commented on src/prompts/evilNeuro.js
> +    'twitchy',
```suggestion
    '"Twitchy"',
```

2023-06-10 21:16 UTC, cjmaxik commented on src/prompts/evilNeuro.js
> +    'mentions her experiments on humans',
Too long

2023-06-10 21:20 UTC, tioopental commented on src/prompts/evilNeuro.js
> +    'mentions her missing cat',
ye looks better

2023-06-11 12:07 UTC, cjmaxik approved these changes

2023-06-11 12:08 UTC, merged