Neuro-sama plays Minecraft
cjmaxik/everyday-neuro-bingo pull request #60
Opened 2023-06-29 18:03 UTC by tioopental

- [x] fill prompts

- [x] emotes

- [x] more sounds

2023-06-29 18:05 UTC, cjmaxik commented on src/components/StreamTypeLinks.vue
> +  { to: 'minecraftNeuro', text: 'Neuro plays minecraft' }
Hear me out...
```suggestion
  { to: 'miNeuro', text: 'Neuro plays minecraft' }
```

2023-06-29 18:28 UTC, cjmaxik requested changes

2023-06-29 18:28 UTC, cjmaxik commented on public/assets/images/minecraftNeuro/minecraftskin.png
Note to myself - crop/resize

2023-06-29 18:28 UTC, cjmaxik commented on public/assets/images/minecraftNeuro/neurolava.png
We need an image with transparency around the character, or else won't look good

2023-06-29 18:28 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +  name: 'Minecraft Neuro',
```suggestion
  name: 'Neuro plays Minecraft',
```

2023-06-29 18:28 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +  sounds: [
I can add basic Neuro sounds here (if nothing new is found)

2023-06-29 18:34 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +  sounds: [
I have 2 or 3 sounds in mind, gonna work on them friday evening/saturday morning

2023-06-29 18:36 UTC, tioopental commented on public/assets/images/minecraftNeuro/neurolava.png
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/25345920/6f89bada-a4b9-49a9-b0be-77c6effc3738)

2023-06-30 07:24 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    // general prompts from Neuro
The general prompts section is kinda stale by now, maybe shake it up a little bit?

2023-06-30 07:25 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'Technical Difficulties screen',
We have a more generalized prompt already, this is an old variant of it.

2023-06-30 07:26 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'donowalls LomiBox specifically',
We have "donowalled" already + Lomi might not be with us on a stream, so it will be ☠️

2023-06-30 07:28 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'obsessively mines obsidian barehandedly',
Make it shorter

2023-06-30 07:28 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'gets /kill\'ed',
"killed by Vedal" maybe?

2023-06-30 19:39 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'Technical Difficulties screen',
Right, I forgot about it

2023-06-30 19:40 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'donowalls LomiBox specifically',
I know, I just love this prompt <3

2023-06-30 20:30 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'obsessively mines obsidian barehandedly',
Fixed

2023-06-30 20:31 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'gets /kill\'ed',
Sounds better ye

2023-06-30 21:36 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +  sounds: [
Done

2023-07-01 08:38 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +  sounds: [
I will leave this as is for now. But, for the future, I imagined these sounds as one-off sound alerts, not full-fledged phrases.

2023-07-01 09:18 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'obsessively hand-mines obsidian',
How will we determine if it is "obsessive"?

2023-07-01 09:20 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'obsessively hand-mines obsidian',
Mines obsidian, Vedal stops her and she goes for it again

2023-07-01 09:23 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'obsessively hand-mines obsidian',
This will require our confirmation in the chat then. Let's try to come up with a more intuitive prompt.

2023-07-01 09:25 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'dies from hostile\xa0mob',
I forgor how to play Minecraft. Is it even possible to have a trip in Nether without **making** a portal?

2023-07-01 09:26 UTC, tioopental commented on src/prompts/minecraftNeuro.js
> +    'dies from hostile\xa0mob',
As far as I remember the portal is on the map, she destroys it everytime by mining obsidian tho

2023-07-01 10:13 UTC, cjmaxik commented on src/prompts/minecraftNeuro.js
> +    'dies from hostile\xa0mob',
Gotcha, the prompt stays then

2023-07-01 10:28 UTC, tioopental commented
Board is bussin'

2023-07-01 10:49 UTC, tioopental commented
![image](https://github.com/cjmaxik/everyday-neuro-bingo/assets/25345920/ec21cf46-984d-4b3b-960f-5a9771968ac8)

2023-07-01 10:50 UTC, cjmaxik approved these changes

2023-07-01 10:50 UTC, merged